version: '3.7'

services:
 database:
  image: postgres
  container_name: db_go_finances
  restart: always
  ports:
   - ${DB_PORT}:${DB_PORT}
  environment:
   - POSTGRES_USER=${DB_USER}
   - POSTGRES_PASSWORD=${DB_PASSWORD}
   - POSTGRES_DB=${DB_NAME}
  volumes:
   - pgdata:/data/postgres

 app:
  container_name: app_api
  build: .
  ports:
   - ${API_PORT}:${API_PORT}

  volumes:
   - .:/home/services
  depends_on:
   - database

volumes:
 pgdata:
